### PR TITLE
Solution submission

### PR DESCRIPTION
**Pull request by 0x0is1**
There are no clear details for project submission in this repository. I believe this is how we have to submit it?
Solution: https://github.com/0x0is1/ArihantAI

### CODE REVIEW

**Comment by rajankakkar01** [comment]
yes , you are right . since project is based on different themes , so any one can choose any theme and based on the theme , any project idea. so it is deliberatly kept open.

**Comment by 0x0is1** [comment]
@rajankakkar01 Sir, in that case this pull request contains commits with submission details of my solution and team.
Would you merge it to the main branch or it will get evaluated from PR list only with no merging?

**Comment by Neil-05** [comment]
[Byte Brigade BuildAThon.zip](https://github.com/rajankakkar01/CIC-3.0-Build-a-thon/files/14785054/Byte.Brigade.BuildAThon.zip)

@rajankakkar01 
By 
Neil Parkhe :- 12215394
Harsh Yadav :- 12220839
Harsh Jangra :-12221870

**Comment by brajesh350194** [comment]
[Hackathon 2.0zip.zip](https://github.com/rajankakkar01/CIC-3.0-Build-a-thon/files/14786511/Hackathon.2.0zip.zip)

Brajesh Kumar
Ashotosh patel
Vaibhav sharma

**Comment by BHARATHKUMARREDDY2004** [comment]
[Disaster Management Chatbot by Syntax Scorers.zip](https://github.com/rajankakkar01/CIC-3.0-Build-a-thon/files/14789355/Disaster.Management.Chatbot.by.Syntax.Scorers.zip)

Bharath Kumar Reddy Vemireddy : 12216505
Rama Krishna Jakkula : 12215918

**Comment by 0x0is1** [comment]
@rajankakkar01 sir, in case you missed, i have submitted my solution detail through this PR. Mind reviewing or giving any comment on it?

**Comment by rajankakkar01** [comment]
Actually , the case was that , everyone knows that , its hard to one by one go to others profile and check , and that too looking from google form 's list that who has submitted or not . So the idea was to allow people to create a Pull request , ofcourse it wouldn't be merged.  but @0x0is1 i like the way you had your PR.  

And from your PR I can easily go to your profile and see and even see your friends profile who is in the team

The Main thing was that , to make you people get aware of how PR works . if someone doesn't know , then a 5 mins video is enough to learn.


And i will check everyone's files. Those who have submitted ZIP files , should understand that if i had to check by downloading everyone's files then why PR was told to do.  So one should understand that , fork the repo , upload your files in the repo and then raise a PR . 

btw @brajesh350194 @BHARATHKUMARREDDY2004 I have recieved your PR , so no need to put ZIP here. but its okay now.

Rest assured , I will check everyone's files and tell accordingly. relax.  Best of luck

**Comment by 0x0is1** [comment]
Sir, by when we will receive selected nominees list and where? What will be the selection criteria? Please share.

**Comment by rajankakkar01** [comment]
You will get confirmation by tomorrow morning

**Comment by 0x0is1** [comment]
Got it. Thank you, sir.

**Comment by 0x0is1** [comment]
@rajankakkar01 sorry for the inconvenience but is there any update on this, sir? We were expected to get some information regarding this by yesterday.

**Pull request closed without merging**
